export const OPEN_SUCCESS_ALERT = "OPEN_SUCCESS_ALERT";
export const CLOSE_SUCCESS_ALERT = "CLOSE_SUCCESS_ALERT";
export const OPEN_INFO_ALERT = "OPEN_INFO_ALERT";
export const CLOSE_INFO_ALERT = "CLOSE_INFO_ALERT";
export const OPEN_ERROR_ALERT = "OPEN_ERROR_ALERT";
export const CLOSE_ERROR_ALERT = "CLOSE_ERROR_ALERT";
